[package]
name = "cloudformatious-cli"
version = "0.1.0-rc.1"
authors = ["Chris Connelly <chris@connec.co.uk>"]
license = "MIT"
edition = "2018"
description = "A CloudFormation CLI that won't make you cry"
repository = "https://github.com/connec/cloudformatious-cli"

[[bin]]
name = "cloudformatious"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.2"
cloudformatious = "=0.0.7"
colored = "2.0.0"
futures-util = "0.3.14"
lazy_static = "1.4.0"
regex = "1.5.4"
rusoto_cloudformation = "0.46.0"
rusoto_core = "0.46.0"
rusoto_credential = "0.46.0"
serde_json = "1.0.64"
tokio = { version = "1.5.0", features = ["macros"] }
