# This workflow performs a cached build of osxcross. The idea is to run it on your default branch
# (e.g. `main`) to prepare a cache that can then be consumed from other branches/tags.

name: Cache osxcross

on:
  push:
    branches: master

jobs:
  build:
    name: Cache osxcross
    runs-on: ubuntu-latest
    env:
      SDK_VERSION: '12.3'
    steps:
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ runner.temp }}/osxcross
          key: osxcross-${{ runner.os }}-${{ env.SDK_VERSION }}
      - name: Build osxcross
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail

          sudo apt-get update && sudo apt-get install -y \
            clang \
            g++ \
            gcc \
            libgmp-dev \
            libmpc-dev \
            libmpfr-dev \
            zlib1g-dev

          git clone https://github.com/tpoechtrager/osxcross "$RUNNER_TEMP/osxcross"

          sdk_file="MacOSX$SDK_VERSION.sdk.tar.xz"
          wget -nc "https://github.com/joseluisq/macosx-sdks/releases/download/$SDK_VERSION/$sdk_file" -O "$RUNNER_TEMP/osxcross/tarballs/$sdk_file"

          UNATTENDED=yes "$RUNNER_TEMP/osxcross/build.sh"
