name: cargo-publish

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  cargo-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: cargo publish
        run: cargo publish --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }
